# gazebo_control.yaml

gazebo_ros_control:
  pid_gains:
    joint_1:
      p: 1.0
      i: 0.1
      d: 0.05
    joint_2:
      p: 1.2
      i: 0.08
      d: 0.01
    joint_3:
      p: 0.8
      i: 0.12
      d: 0.06
    joint_4:
      p: 1.5
      i: 0.05
      d: 0.03
    joint_5:
      p: 0.9
      i: 0.1
      d: 0.07
    joint_6:
      p: 1.0
      i: 0.15
      d: 0.08
    joint_7:
      p: 0.7
      i: 0.08
      d: 0.04
